### ISSUE TITLE
Useful/Desired New FGPU2 Features

### ISSUE THREAD

**Issue by Robadob** [primagesheffield/flamegpu2-neuroblastoma#2]
Just a checklist of features that are missing from FGPU2 which could/would benefit this project.

- [ ] Bespoke arg parsing (https://github.com/FLAMEGPU/FLAMEGPU2/issues/257)
- [ ] Device agent init functions (https://github.com/FLAMEGPU/FLAMEGPU2/issues/329)
- [ ] GLM vector reductions in Py API (https://github.com/FLAMEGPU/FLAMEGPU2/issues/733)

This list can be extended as more are realised
